# Site settings
title: Foclóir na nGaylgeoirí
description: Foclóir de théarmaíocht LADTA+
brand: An Gèidheal Ùr
brand-link: https://angeidhealur.scot/
brand-tagline: Geàrr-chunntas sgrìobhte de naidheachdan LGDTCEN+ ionadail, nàiseanta ‘s bho air feadh an t-saoghail.
# baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://focloir.lgbt" # the base hostname & protocol for your site
excerpt_separator: <!--more-->

#footer
author-name: Crìstean MacMhìcheil
author-website: "https://criomagan.scot"

#social
mastodon: https://abairthusa.scot/@angeidhealur
instagram: https://www.instagram.com/angeidhealur
threads: https://www.threads.net/@angeidhealur
email: fios@angeidhealur.scot

# Build settings
markdown: kramdown
permalink: /:year-:month-:day-:title/
paginate: 12
paginate_path: /duilleag-:num/

# Ruby Gems
plugins:
  - jekyll-paginate
  - jekyll-feed

collections:
  faclair:
    output: true
    permalink: /:path/